<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net9.0-windows;net10.0-windows</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>Library to read and write to raw disks in Windows, something that can be tricky from time to time</Description>
    <PackageTags>Raw-disk;Disk</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\external\DeviceIOControlLib\DeviceIOControlLib\DeviceIOControlLib.csproj" />
  </ItemGroup>

</Project>
